#426-fund_information-fix
NUTFes/FinanSu pull request #444
Opened 2023-02-06 01:59 UTC by Kubosaka

#426  

resolve #426

# 概要

- fund_informationがcreate,updateされたときに、そのレコードを返す修正
- fund_informationのメソッドのリファクタリング
- fund_informationのswaggerの追加

# 画面スクリーンショット等
<img width="740" alt="スクリーンショット 2023-02-06 10 54 43" src="https://user-images.githubusercontent.com/115447919/216864478-ba787c10-3b86-47a7-800a-7aabe33cad8e.png">

# テスト項目
- swaggerでAPIの動作に問題がないか確認する
- ファイルの変更点を確認し、メソッド名が適切かチェックする
- 

# 備考

2023-02-06 07:02 UTC, Kubosaka commented
エンドポイントの修正行いました

2023-02-06 15:06 UTC, ryuseifujisaki requested changes
動作は問題ないです！
細かいところの修正をお願いします！

2023-02-06 15:06 UTC, ryuseifujisaki commented on api/docs/docs.go
> +                        "description": "teacher_id",
```suggestion
                        "description": "teacher_id",
                        "required": true,
```
DB見ると、`teacher_id`もnot nullなので、`required`入れてよさそうですね

2023-02-06 15:06 UTC, ryuseifujisaki commented on api/docs/docs.go
> +                        "description": "price",
```suggestion
                        "description": "price",
                        "required": true,
```
priceにも入れてよさそう

2023-02-06 15:06 UTC, ryuseifujisaki commented on api/docs/docs.go
> +                        "required": true,
```suggestion
```
逆にremarkは`nullable`なので不必要

2023-02-06 15:06 UTC, ryuseifujisaki commented on api/docs/docs.go
> +                        "description": "teacher_id",
```suggestion
                        "description": "teacher_id",
                        "required": true,
```
上記同様

2023-02-06 15:06 UTC, ryuseifujisaki commented on api/docs/docs.go
> +                        "description": "price",
```suggestion
                        "description": "price",
                        "required": true,
```
同様

2023-02-06 15:06 UTC, ryuseifujisaki commented on api/docs/docs.go
> +                        "required": true,
```suggestion
```
不必要

2023-02-07 06:39 UTC, ryuseifujisaki approved these changes
変なスペースだけ修正してmergeでよさそうです！

2023-02-07 06:39 UTC, ryuseifujisaki commented on api/externals/repository/fund_information_repository.go
> +	 		fund_informations(
```suggestion
			fund_informations(
```
変なスペースありました。これはgithub上で修正でよさそう

2023-02-07 06:41 UTC, merged