[fix]spnseractibitiesのリプレイス
NUTFes/FinanSu pull request #445
Opened 2023-02-06 06:29 UTC by KazumaSun

# 対応Issue
#421 

resolve #0
resolve #421 

# 概要

sponseractivityの内容をtailwindにリプレイス

# 画面スクリーンショット等

- `URL`
スクリーンショット
![finansu1](https://user-images.githubusercontent.com/68796591/216898836-363fa1bf-c7e8-4c3e-8e39-cb95ebfd84b5.png)

# テスト項目

-
-
-

# 備考

2023-02-09 09:04 UTC, YushiroDodo63 requested changes
@KazumaSun 
以下の対応をお願いします！
修正箇所
- [x] 全体を囲うCardの追加
- タイトル・年度のセレクトボックス・追加ボタン
  - [x] タイトルのフォントサイズ
  - [x] セレクトボックスのサイズ
  - [x] 登録ボタンの位置
- テーブルのデザイン
  - [x] テーブルヘッダーの線の太さ・色
  - [x] 行の高さ
  - [x] 文字色
  - [x] テーブルの一番下の線を追加
  - [x] 削除ボタンの追加

2023-02-09 09:20 UTC, YushiroDodo63 commented
やること
- `view/next-project/src/pages/purchaseorders/index.tsx` の Card, Title の使い方を真似て実装する
- 上記と同じファイルの table, th, tbody のclassName を参考にしてテーブルのデザインを実装する
- RegistButton, EditButton, DeleteButton などに関しては、 `view/next-project/src/components/purchaseorders` のディレクトリをコピーして必要そうなファイルを残してそれを呼び出すような実装に変更する
ボタンを押した際の挙動に関しては、別issueで対応する

2023-03-26 15:36 UTC, YushiroDodo63 requested changes
いくつかレビューしました〜
tailwindのスタイルに関しては見れてないです。
レビューした点に関しても、全部完全に見れた訳じゃないのでコメントした所と同じような所があればその修正もお願いします〜🙇‍♂️

2023-03-26 15:36 UTC, YushiroDodo63 commented on view/next-project/src/components/sponsoractivities/DeleteModal.tsx
> +  };
この関数に props.id を渡しとるなら、引数なくても良いかも！

2023-03-26 15:36 UTC, YushiroDodo63 commented on view/next-project/src/components/sponsoractivities/EditModal.tsx
> +  const [user, setUser] = useState<User[]>([]);
複数のデータが入るなら変数名も複数形の方が適切かもです！

2023-03-26 15:36 UTC, YushiroDodo63 commented on view/next-project/src/components/sponsoractivities/EditModal.tsx
> +  }, []);
モーダルでデータを取得するのはあんま良くない気がするんで、ページ側（ssr時）でデータを取得して props でデータを渡した方がいいかもです！

2023-03-26 15:36 UTC, YushiroDodo63 commented on view/next-project/src/components/sponsoractivities/EditModal.tsx
> +  }, [formData]);
ここは消して良さそう！

2023-03-26 15:36 UTC, YushiroDodo63 commented on view/next-project/src/components/sponsoractivities/OpenEditModalButton.tsx
> +      ) : null}
他のところでもそうだけど、elseがnullなら三項演算子は ? じゃなくて && の方いいかも！

2023-03-26 15:36 UTC, YushiroDodo63 commented on view/next-project/src/components/sponsoractivities/SponsorActivitiesAddModal.tsx
> +  }, []);
これも同じでモーダル内でAPI叩かない方がいいかもです〜

2023-03-26 15:36 UTC, YushiroDodo63 commented on view/next-project/src/components/sponsoractivities/SponsorActivitiesAddModal.tsx
> +  const [users, setUsers] = useState<User[]>([]);
ここの変数名も複数形で！

2023-03-26 15:36 UTC, YushiroDodo63 commented on view/next-project/src/components/sponsoractivities/SponsorActivitiesAddModal.tsx
> +  };
closeModalとreloadをaddSponsor内でやらん理由ってあったりする？

2023-03-26 15:36 UTC, YushiroDodo63 commented on view/next-project/src/pages/sponsoractivities/index.tsx
> +        <meta name='viewpoinst' content='initial-scale=1.0, width=device-width' />
これってどういう意図で変更した感じー？

2023-03-27 07:27 UTC, imaimai17468 commented on view/next-project/src/pages/sponsoractivities/index.tsx
> +        <meta name='viewpoinst' content='initial-scale=1.0, width=device-width' />
一覧をつけてもいいんですが、どのページも一覧なので、特段このページに一覧をつける必要はないかなと思いました

2023-03-27 07:41 UTC, imaimai17468 commented on view/next-project/src/components/sponsoractivities/SponsorActivitiesAddModal.tsx
> +  };
特にないですが、closeModalとreloadがsubmit内にある方が、db叩いたあとの流れがまとめてみれていいのかなと思います
どっちでも問題ないです！

2023-03-27 07:44 UTC, imaimai17468 commented on view/next-project/src/components/sponsoractivities/DeleteModal.tsx
> +  };
[[fix] props.idを直接渡すようにする](https://github.com/NUTFes/FinanSu/pull/445/commits/eaa7e4c1d654c1d548e7ced72e1db9a6375dfaea)　で対応しました！

2023-03-27 07:45 UTC, imaimai17468 commented on view/next-project/src/components/sponsoractivities/EditModal.tsx
> +  }, [formData]);
[[fix] デバッグ文のけしわすれ](https://github.com/NUTFes/FinanSu/pull/445/commits/d468c921cd748e56e4a769e1f475007c27d4817d)　で対応しました

2023-03-27 07:45 UTC, imaimai17468 commented on view/next-project/src/components/sponsoractivities/EditModal.tsx
> +  }, []);
[[fix] pageから情報を取得してedit modalに渡す](https://github.com/NUTFes/FinanSu/pull/445/commits/9cfb2cf583aa7943b9957631fbb31649c4c793e2)　で対応しました！

2023-03-27 07:45 UTC, imaimai17468 commented on view/next-project/src/components/sponsoractivities/EditModal.tsx
> +  const [user, setUser] = useState<User[]>([]);
https://github.com/NUTFes/FinanSu/pull/445#discussion_r1148913839　で対応した際に削除しました！

2023-03-27 07:46 UTC, imaimai17468 commented on view/next-project/src/components/sponsoractivities/OpenEditModalButton.tsx
> +      ) : null}
[[fix]isOpenから派生する三項演算子を&&に置き換える](https://github.com/NUTFes/FinanSu/pull/445/commits/9278290cbbce714bba80b5ea4455a77aedf5f21a)　で対応しました！

2023-03-27 07:50 UTC, imaimai17468 commented on view/next-project/src/components/sponsoractivities/SponsorActivitiesAddModal.tsx
> +  }, []);
このaddModalってuseUIを使って表示させていて、Layout.tsxから呼び出しているので、ページから叩いて渡すとなると_app.tsxでgetServerSidePropsをする必要があるんですが、これは不味そうな気がします
このままにするか、addModalをuseUIの管理下から外すかなんですが、どちらがいいですかね？

2023-03-27 07:50 UTC, imaimai17468 commented on view/next-project/src/components/sponsoractivities/SponsorActivitiesAddModal.tsx
> +  const [users, setUsers] = useState<User[]>([]);
[[fix] stateの名前を複数形にする](https://github.com/NUTFes/FinanSu/pull/445/commits/db9c1f8b9f1d5e6e74c975a1861899b447a01814)　で対応しました！

2023-03-27 09:48 UTC, imaimai17468 commented on view/next-project/src/pages/sponsoractivities/index.tsx
> +        <meta name='viewpoinst' content='initial-scale=1.0, width=device-width' />
サイドメニューには一覧をつけずに、ページ名とカードのタイトルには一覧をつけた方がわかりやすそうなので修正しました！

[[fix] タイトルには一覧をつける](https://github.com/NUTFes/FinanSu/pull/445/commits/dbfc61b1bb8ac57be5097668f7f5d5f8178a93f6)

2023-03-31 09:46 UTC, YushiroDodo63 commented on view/next-project/src/components/sponsoractivities/EditModal.tsx
> +            </option>
select の option でこういう情報見れるのいい配慮すぎる 👏

2023-03-31 09:48 UTC, YushiroDodo63 approved these changes
LGTM!!

2023-03-31 10:20 UTC, merged