428-purchase_order
NUTFes/FinanSu pull request #446
Opened 2023-02-06 06:55 UTC by Kubosaka

#428 

resolve #428

# 概要

- purchase_orderのメソッドのリファクタリング
- メソッドの修正(create,udateしたレコードを返す)
- swaggerへのpurchase_orderの追加
- クエリ修正

# 画面スクリーンショット等
<img width="636" alt="スクリーンショット 2023-02-06 15 54 03" src="https://user-images.githubusercontent.com/115447919/216903215-64955586-25a8-4683-81fb-fdcb9630d34f.png">

# テスト項目
- APIの動作確認
- メソッドのリファクタリングが適切か

2023-02-06 07:14 UTC, Kubosaka commented
エンドポイントも修正してます。確認お願いします。
<img width="636" alt="スクリーンショット 2023-02-06 16 14 19" src="https://user-images.githubusercontent.com/115447919/216907333-7ff900f3-c6c6-4bb3-abfa-05505908d0fa.png">

2023-02-07 03:11 UTC, Kubosaka commented
#426 の修正を受けてこちらも修正しました

2023-02-07 06:31 UTC, ryuseifujisaki requested changes
メソッド名を少し変えるくらいですかね
動作は問題ないです

2023-02-07 06:31 UTC, ryuseifujisaki commented on api/internals/usecase/purchase_order_usecase.go
>  	rows, err := p.rep.AllOrderWithUser(c)
```suggestion
	rows, err := p.rep. AllUserInfo(c)
```
repositoryの修正に倣うとこんな感じになる

2023-02-07 06:31 UTC, ryuseifujisaki commented on api/internals/usecase/purchase_order_usecase.go
> +	row, err := p.rep.FindWithOrderItem(c, id)
```suggestion
	row, err := p.rep.FindUserInfo(c, id)
```

2023-02-07 06:31 UTC, ryuseifujisaki commented on api/externals/controller/purhcase_order_controller.go
>  func (p *purchaseOrderController) IndexOrderWithUserItem(c echo.Context) error{
```suggestion
func (p *purchaseOrderController) IndexOrderDetail(c echo.Context) error{
```
こんな感じのメソッド名がよさそう

2023-02-07 06:31 UTC, ryuseifujisaki commented on api/externals/controller/purhcase_order_controller.go
>  func (p *purchaseOrderController) ShowOrderWithUserItem(c echo.Context) error{
```suggestion
func (p *purchaseOrderController) ShowOrderDetail(c echo.Context) error{
```
こんな感じのメソッド名がよさそう

2023-02-07 07:05 UTC, Kubosaka commented
修正しましたー

2023-02-07 14:33 UTC, ryuseifujisaki requested changes
変数名だけgithub上で修正してmergeでよさそうですね

2023-02-07 14:33 UTC, ryuseifujisaki commented on api/externals/controller/purhcase_order_controller.go
> +	orderWithUserItems, err := p.u.GetPurchaseOrderDetails(c.Request().Context())
```suggestion
	orderDetails, err := p.u.GetPurchaseOrderDetails(c.Request().Context())
```
ここの変数名も変えてよさそうですね

2023-02-07 14:33 UTC, ryuseifujisaki commented on api/externals/controller/purhcase_order_controller.go
> +	orderWithUserAndItem , err := p.u.GetPurchaseOrderDetailByID(c.Request().Context(),id)
```suggestion
orderDetail , err := p.u.GetPurchaseOrderDetailByID(c.Request().Context(),id)
```
ここも変えてよさそう

2023-02-08 02:35 UTC, merged