472 expenseテーブルの作成
NUTFes/FinanSu pull request #489
Opened 2023-03-09 01:52 UTC by Kubosaka

#472 

resolve #472 

# 概要

- expenseテーブルの作成
- expenseに関するCRUD APIの作成
- expenseのtotalPriceの更新APIの作成
- expenseに紐づくpurchase_itemを取得するAPIの作成
- purchase_orderにexpense_idのカラム追加

# 画面スクリーンショット等

スクリーンショット
<img width="627" alt="スクリーンショット 2023-03-09 10 40 59" src="https://user-images.githubusercontent.com/115447919/223893399-2a00bddb-3ca2-48f3-8c69-a85c266cbd1a.png">
<img width="617" alt="スクリーンショット 2023-03-09 10 42 05" src="https://user-images.githubusercontent.com/115447919/223893536-ae79009a-c8f8-460b-9039-ff10b1940b63.png">

# テスト項目

- swaggerでexpenseに関するAPIを確認する
> - `docker compose down -v`でコンテナを削除する←データベースを初期化するため
> - `make run-api`でdbとapiコンテナを立ち上げる
> - ブラウザで`http://localhost:1323/swagger/index.html#/`にアクセスし、`/expense`に関するAPIを確認する
> - `puchase_items`,`purchase_orders`,`purchase_reports`などにもデータを追加したり修正したりしてexpenseのtotalPriceが更新されるか確認する。
- コードの確認をする
- swaggerを触りながらデータの紐づきが正しいか確認する

# 備考
APIの説明
`GET` `/expense`
expenseのtotalPriceを更新し、expenseテーブルの一覧を表示

`POST` `/expense`
expenseテーブルにレコードを追加、現在は支出元(name)と年度(year_id)からレコードを生成し、支出額(totalPrice)にはデフォルトで0が入る。
作成したレコードが返ってくる。

`GET` `/expense/details`
expenseテーブルとそれに紐づいたpurchase_itemsを金額の大きい順に3件取得する。取得したpuchase_itemsはid,itemしか持っていない。

`GET` `/expense/{id}`
idよりexpenseのレコードを1件返す

`PUT` `/expense/{id}`
idよりexpenseのレコードを修正する。
修正したレコードが返ってくる。

`DELETE` `/expense/{id}`
idよりexpenseのレコードを削除する。

`GET` `/expense/{id}/details`
idよりpurchase_itemsの紐づいたexpenseのレコードを1件返す

2023-03-16 16:49 UTC, YushiroDodo63 requested changes
@Kubosaka 
3点だけ修正お願いします！

- [ ] URLは `/expense` → `/expenses` の方が適切かもです！
- [ ] `purchaseItem` は `item` しかないけど、他の値（ `price`, `quantity`, `detail`, `url` ）も欲しいかもです！というのも、支出用一覧ページから詳細モーダルを開くときに購入物品の詳細情報とかもあった方がありがたいかもと思ったので！（なんなら、紐づくpurchaseOrder, purchaseReportもあった方がいいかも）
- [ ] ↓の画像の `purchaseItem` は `purchaseItems` の方が適切かも？と思ったので修正お願いします！
<img width="483" alt="スクリーンショット 2023-03-17 1 45 22" src="https://user-images.githubusercontent.com/71711872/225691975-4c151b36-a67b-45bf-a4ff-9afdacaf1314.png">

2023-03-18 16:56 UTC, Kubosaka commented
@YushiroDodo63 
修正してpushしましたが、PR別れちゃいました。以前間違ってmergeしたとかの関係かなって思います。
↓
https://github.com/NUTFes/FinanSu/pull/491
お願いします

2023-03-31 16:00 UTC, imaimai17468 approved these changes
LGTM

2023-04-04 15:28 UTC, YushiroDodo63 approved these changes
LGTM!!

2023-04-05 01:13 UTC, merged