協賛スタイルを登録・編集
NUTFes/FinanSu pull request #490
Opened 2023-03-11 14:42 UTC by imaimai17468

# 対応Issue

resolve #0

# 概要

# 画面スクリーンショット等

- `URL`
スクリーンショット

# テスト項目

-
-
-

# 備考

2023-03-16 17:23 UTC, YushiroDodo63 requested changes
協賛関連全部（ファイル名、型名、変数名など）において、
sponsor → sponser に変更して欲しいです！
APIも間違えとるけん分かりにくいかもやけど、[HackMD](https://hackmd.io/AJ1aepJ7SCKM7W9u1D7pMg?view#Sponser%EF%BC%88%E5%8D%94%E8%B3%9B%E9%96%A2%E4%BF%82%EF%BC%89)を正としたいので！

2023-03-16 17:23 UTC, YushiroDodo63 commented on view/next-project/src/components/sponsorstyles/EditModal.tsx
> +  });
ここはこんな感じに簡略化できるかも？
```suggestion
  // 協賛スタイルのリスト
  const [formData, setFormData] = useState<SponsorStyle>(props.sponsorStyle);
```

2023-03-20 14:59 UTC, imaimai17468 commented on view/next-project/src/components/sponsorstyles/EditModal.tsx
> +  });
修正しました！
[58a321e](https://github.com/NUTFes/FinanSu/pull/490/commits/58a321ed5b0de019186761bf269fcd6faab42613)

2023-03-28 06:31 UTC, Kubosaka approved these changes

2023-03-28 09:54 UTC, merged