Feature/kubosaka/615 activity fix
NUTFes/FinanSu pull request #619
Opened 2023-06-23 15:46 UTC by Kubosaka

#615 

resolve #615

# 概要

- activityテーブルにカラム追加,
  - `design` :誰が作ったかを表す。int型　0:学生 1:企業 2:去年
  - `url` :広告データのurl、string型
- カラムの追加に伴うAPIの修正
- 協賛活動ページの表にデザイン追加
  - 作成の矢印からgoogleドライブに遷移 
- 協賛活動ページの追加モーダルの修正
  - デザイン作成とリンクの入力フォーム追加
  - 備考の動的生成の修正
- 協賛活動ページの詳細モーダルの修正
  - デザイン作成とリンクの追加
- 協賛活動ページの修正モーダルの修正
  - デザイン作成とリンクの入力フォーム追加
  - 備考の動的生成の修正
# 画面スクリーンショット等

- `URL`
スクリーンショット
<img width="1156" alt="スクリーンショット 2023-06-24 0 07 15" src="https://github.com/NUTFes/FinanSu/assets/115447919/ea2733fb-9139-4916-91ca-ec19dd5ffb88">
<img width="735" alt="スクリーンショット 2023-06-24 0 07 43" src="https://github.com/NUTFes/FinanSu/assets/115447919/0bb56982-d05c-48b1-8a35-780e8f1c23c0">
<img width="735" alt="スクリーンショット 2023-06-24 0 07 31" src="https://github.com/NUTFes/FinanSu/assets/115447919/1f896e83-1980-4643-9b4d-6ba01eae4b7c">

# テスト項目

- データベースのスキーマを変更しているため、DBコンテナのvolume削除
- `docker compose down -v`
- コンテナ立ち上げ　`docker compose up`
- テスト１　apiの確認
  - swaggerでactivityのapiの動作が適切であるか確認する
- テスト2　協賛活動ページの確認
  - 表にデザインが追加されている確認する
  - デザインのリンクの確認(urlは自分で追加してください)
  - スマホページの確認
- テスト3　追加モーダルの確認
  - 追加モーダルにデザインとurlを入力する欄があるか
  - 備考動的生成の動作の確認(あとで詳しく書きます)
  - レコードの追加ができるか
  - sp版でもできるか
- テスト4　修正モーダルの確認
  - 修正モーダルにデザインとurlを入力する欄があるか
  - 備考動的生成の動作の確認(あとで詳しく書きます)
  - レコードの修正ができるか
  - sp版でもできるか
- テスト4　詳細モーダルの確認
  - 詳細モーダルにデザインとurlがあるか
  - リンクからページに飛べるか、ホバーが効いているか

チェックリスト(適宜追加してください)
- [ ] activityのapiの動作確認
- [ ] 協賛活動ページの表にデザインが追加されているか
- [ ] 表のデザインの矢印からページに飛ぶか
- [ ] 協賛活動のレコードの追加ができるか
- [ ] 協賛活動のレコードの修正ができるか
- [ ] 詳細モーダルにデザインとurlがあるか
- [ ] 備考の動的生成の動作が適切か
- [ ] sp版対応しているか

# 備考

備考の動的生成は追加、修正モーダルでデータを入力する際に入力した内容に応じて備考にテキストのテンプレートを生成します。
今回広告の作成者のカラムが追加されたことにより処理を変更しました。

- オプション
 - クーポンが選択された場合、`<クーポン> [詳細 :  ○○]`が生成
 - ポスターが選択された場合、`<ポスター掲載内容> パンフレット広告拡大`が生成
- デザイン作成
 - 学生が作成が選択された場合、`<パンフレット掲載内容> [企業名 : x],[住所 : x],[HP : x],[ロゴ : x],[営業時間 : x],[電話番号 : x],[キャッチコピー : x],[地図 : x],[その他 :  ] `が生成
 
<img width="697" alt="スクリーンショット 2023-06-24 0 41 22" src="https://github.com/NUTFes/FinanSu/assets/115447919/4b5da413-c7ed-4a7f-a5b3-5edc16ae43c8">

2023-06-24 06:09 UTC, imaimai17468 requested changes
レビューしました！
動作はOK！
部分的に改善できそうなコードについてレビューをつけました！

2023-06-24 06:09 UTC, imaimai17468 commented on view/next-project/src/components/sponsoractivities/SponsorActivitiesAddModal.tsx
> +    };
特定の値を更新する場合は、inputは受け取らなくていいかな
formDataHandlerは汎用化したからそう書いてある感じかな！
```suggestion
  const setFeature = (e: React.ChangeEvent<HTMLSelectElement>) => {
    const newRemarkFeature =
      e.target.value === 'ポスター'
        ? REMARK_POSTER
        : e.target.value === 'クーポン'
        ? REMARK_COUPON
        : '';
    const remarkDesign = formData.design === 0 ? REMARK_PAMPHLET : '';
    setFormData({
      ...formData,
      feature: e.target.value,
      remark: newRemarkFeature + remarkDesign,
    });
  };
```

これを使う場合は
```
<Select value={data.feature} onChange={setFeature}>
```
こんな感じでinputを書かなくてもeventを受け取れる

2023-06-24 06:09 UTC, imaimai17468 commented on view/next-project/src/components/sponsoractivities/SponsorActivitiesAddModal.tsx
> +    };
不要なconsole.logは消した方がいいかも
あとsetFeatureと同様にinputは受け取らなくて大丈夫
```suggestion
  const setDesign = (e: React.ChangeEvent<HTMLInputElement>) => {
    const remarkOption =
      formData.feature === 'ポスター'
        ? REMARK_POSTER
        : formData.feature === 'クーポン'
        ? REMARK_COUPON
        : '';
    const newRemarkDesign = e.target.value === '0' ? REMARK_PAMPHLET : '';
    setFormData({
      ...formData,
      design: Number(e.target.value),
      remark: remarkOption + newRemarkDesign,
    });
  };
```

これを使う場合も
```
onChange={setDesign}
```
みたいにinputを受け取る部分は書かなくて大丈夫

2023-06-24 15:57 UTC, Kubosaka commented
修正した！

2023-06-24 17:15 UTC, Kubosaka commented
デザインが必要ない場合も考えられるため"なし"の状態も追加しました。
↓
`design` :誰が作ったかを表す。int型　0:なし 1:学生 2:企業 3:去年

2023-06-25 01:18 UTC, imaimai17468 requested changes
Lintがいくつかエラー吐いてたので修正お願い！

[この記事](https://zuma-lab.com/posts/eslint-prettier-settings)の**VSCode に ESLint/Prettier 拡張機能を install する**から参考にすると、cmd+sで保存したときに自動でフォーマットが効くからおすすめ！

2023-06-25 01:18 UTC, imaimai17468 commented on view/next-project/src/components/sponsoractivities/DetailModal.tsx
> +import { DESIGNERS } from "@constants/designers";
コードを書く順番としてはimport -> 型定義 -> コード本体がいいな
この行はModalとActivityViewのimportの間にあって欲しい！
多分Lintのエラーにもそう書いてあると思う（Lintでimport順のルールを付けてるので）

2023-06-25 01:18 UTC, imaimai17468 commented on view/next-project/src/components/sponsoractivities/EditModal.tsx
> +import { DESIGNERS, DESIGNER_VALUES } from "@constants/designers";
使ってないimportは消して大丈夫（VSCodeだと薄く灰色になっていると思う）
これも@typeより@constantsディレクトリの方がimport順が上だね

```suggestion
import { DESIGNER_VALUES } from "@constants/designers";
import { SponsorActivity, Sponsor, SponsorStyle, User, ActivityStyle } from '@type/common';
```

2023-06-25 01:18 UTC, imaimai17468 commented on view/next-project/src/components/sponsoractivities/SponsorActivitiesAddModal.tsx
> +            <div className='flex gap-3'>
すまん、レビューでkeyの指定を書いてなかった！
mapで繰り返し表示したところにはkeyを書いておきたい
参考：https://ja.legacy.reactjs.org/docs/lists-and-keys.html

```suggestion
            <div className='flex gap-3' key={designer.id}>
```

2023-06-25 01:18 UTC, imaimai17468 commented on view/next-project/src/pages/sponsoractivities/index.tsx
> +import { DESIGNERS } from "@constants/designers";
この行と、

`import { RiExternalLinkLine } from 'react-icons/ri';`
この行もimport順で怒られているので注意

2023-06-25 01:18 UTC, imaimai17468 commented on view/next-project/src/components/sponsoractivities/EditModal.tsx
> +          <div className='flex gap-3'>
ここもkeyが必要

2023-06-25 07:48 UTC, imaimai17468 approved these changes
LGTM!

2023-06-25 07:48 UTC, merged