協賛活動ページの協賛受取の絞り込みと並び替え機能の実装
NUTFes/FinanSu pull request #640
Opened 2023-08-15 05:39 UTC by Kubosaka

#639 

# 概要

- 協賛金の回収済と未受取の絞り込み機能の実装 https://github.com/NUTFes/FinanSu/commit/699ed0e2f4d885bfa682664b78af35584a4b2ec2
- 協賛活動の並び替え機能の実装 https://github.com/NUTFes/FinanSu/commit/1d18a73ab229b0d8738f6c05f3a129b675424016
  - 作成日時昇順(デフォルト) 
  - 作成日時降順 : 作成日の新しい順 
  - 更新日時昇順 : 更新日の古い順 
  - 更新日時降順 : 更新日の新しい順
  - 協賛金昇順 : 協賛金額合計の少ない順
  - 協賛金降順 : 協賛金額合計の多い順

# 画面スクリーンショット等
<img width="700" alt="スクリーンショット 2023-08-15 14 30 00" src="https://github.com/NUTFes/FinanSu/assets/115447919/3865f587-db5e-45d9-8b80-37792f53e747">
<img width="700" alt="スクリーンショット 2023-08-15 14 30 04" src="https://github.com/NUTFes/FinanSu/assets/115447919/74fcf970-e194-4380-8da8-fbef4f1775df">
<img width="700" alt="スクリーンショット 2023-08-15 14 36 30" src="https://github.com/NUTFes/FinanSu/assets/115447919/be7de0b1-7045-49d6-863e-0b88c020400d">

# テスト項目

- [ ] 協賛活動ページを開いた時、全てになっていて、未受取と回収済を選択することで絞り込みができているか
- [ ] 並び替えのそれぞれ選択した際の並びが合っているか
- [ ]  絞り込みによって、テーブルの下に表示される合計が正しいか
- [ ] スマホページでも動作が問題ないか
- [ ] 絞り込み、並び替えにあったcsvファイルが出力されるか
- [ ] どの順番で絞り込みや並び替えを押しても表示結果に誤りがないか

# 備考

2023-08-15 14:04 UTC, imaimai17468 requested changes
レビューしました！
少しずつロジックが長くなってきたので、フィルター内容（回収済み / 降順昇順）とかを受け取って、それに対応した協賛活動を返す関数とかを実装してもいいかも〜

2023-08-15 14:04 UTC, imaimai17468 commented on view/next-project/src/pages/sponsoractivities/index.tsx
> +  }, [filteredSponsorActivitiesViews, selectedIsDone]);
何個も数珠繋ぎで依存させてしまうと、その分レンダリング嵩むので、できれば一つに統一したいね〜

```suggestion
  const sortedAndFilteredSponsorActivitiesViews = useMemo(() => {
    let filtered = props.sponsorActivitiesView.filter((sponsorActivitiesItem) => {
      return sponsorActivitiesItem.sponsorActivity.createdAt?.includes(selectedYear);
    });

    switch (selectedIsDone) {
      case 'false':
        filtered = filtered.filter((item) => !item.sponsorActivity.isDone);
        break;
      case 'true':
        filtered = filtered.filter((item) => item.sponsorActivity.isDone);
        break;
      default:
        break;
    }

    switch (selectedSort) {
      case 'createDesSort':
        return [...filtered].sort(
          (a, b) =>
            new Date(b.sponsorActivity.createdAt || 0).getTime() -
            new Date(a.sponsorActivity.createdAt || 0).getTime(),
        );
      case 'updateSort':
      case 'updateDesSort':
        return [...filtered].sort(
          (a, b) =>
            (selectedSort === 'updateSort' ? 1 : -1) *
            (new Date(a.sponsorActivity.updatedAt || 0).getTime() -
              new Date(b.sponsorActivity.updatedAt || 0).getTime()),
        );
      case 'priceSort':
      case 'priceDesSort':
        return [...filtered].sort((a, b) => {
          const aPrice = a.styleDetail.reduce((sum, style) => sum + style.sponsorStyle.price, 0);
          const bPrice = b.styleDetail.reduce((sum, style) => sum + style.sponsorStyle.price, 0);
          return (selectedSort === 'priceSort' ? 1 : -1) * (aPrice - bPrice);
        });
      default:
        return filtered;
    }
  }, [props, selectedYear, selectedIsDone, selectedSort]);
```

2023-08-15 14:04 UTC, imaimai17468 commented on view/next-project/src/pages/sponsoractivities/index.tsx
> +      filteredIsDoneSponsorActivitiesViews?.map((sponsorActivityItem) => {
最終的に表示させてるのは`sortedSponsorActivitiesViews `だから、そっちを使ったほうが今後`sortedSponsorActivitiesViews `を修正した時にバグを起こさないから安全かな

2023-08-15 14:04 UTC, imaimai17468 commented on view/next-project/src/pages/sponsoractivities/index.tsx
> +              {filteredIsDoneSponsorActivitiesViews.length > 0 && (
sortedSponsorActivitiesViewsを使うのかfilteredIsDoneSponsorActivitiesViewsを使うのかは統一しよう！（できれば表示させてる方に統一させたいね）

2023-08-16 08:06 UTC, Kubosaka commented
修正しました！

2023-08-17 02:52 UTC, imaimai17468 approved these changes
LGTM

2023-08-17 02:52 UTC, merged