[feat]購入報告に購入者の追加
NUTFes/FinanSu pull request #642
Opened 2023-08-17 07:48 UTC by Kubosaka

#641 

# 概要

- purchaseReportにbuyerカラムの追加 https://github.com/NUTFes/FinanSu/commit/dabb3e5831e05dc7c0a9c2c3709759941924f406
- カラム追加に伴うapiの修正 https://github.com/NUTFes/FinanSu/commit/1368bbab3b99368fbcf016191194c1a1c33f2a27 https://github.com/NUTFes/FinanSu/commit/ad91aa86df04bded119efd08a663f69800116fd0
- swaggerにカラム追加 https://github.com/NUTFes/FinanSu/commit/e5811e351fc11b0977e54e06cb0c890cab8d3c89
- 購入申請ページに表示 https://github.com/NUTFes/FinanSu/commit/dc1f1804e2f470ee225e1230bb946c2b2ec88f44
- 詳細モーダルに表示 https://github.com/NUTFes/FinanSu/commit/5de8efc86814f247fa341a34d2160123c8baa03d
- 購入申請の追加モーダルに購入者のフォームの追加 https://github.com/NUTFes/FinanSu/commit/1dd86bd196d59e07fec912f071be3ad59b798459
- 編集モーダルに購入者のフォーム追加 https://github.com/NUTFes/FinanSu/commit/dc65bd71aeb4edfced235f4562c830987795c450
- csv出力にカラム追加 https://github.com/NUTFes/FinanSu/commit/d73711f2a5cc12282c3c34403a791d0c503dc172
- 本番環境用のクエリの作成 https://github.com/NUTFes/FinanSu/commit/d8883caa2263c52847076d1f7332c5f58d13cf50
- 購入報告に関するapiをクエリではなく、bodyで受け取るようにした https://github.com/NUTFes/FinanSu/commit/0bf0fce7f5920a4939865c2d0b0d2462ab6edba6 https://github.com/NUTFes/FinanSu/commit/525fd0518527c1811191568bc8d8a8ad42053a1b https://github.com/NUTFes/FinanSu/commit/c3a81153d50be16fca366fe096ce8099a2435b93

# 画面スクリーンショット等
<img width="1127" alt="スクリーンショット 2023-08-17 16 41 30" src="https://github.com/NUTFes/FinanSu/assets/115447919/ed504ee3-03bb-4903-9d7f-3ed39e9271a0">
<img width="760" alt="スクリーンショット 2023-08-17 16 41 42" src="https://github.com/NUTFes/FinanSu/assets/115447919/6aa058a0-fe2a-4148-a5b9-fd3dd239fda0">
<img width="760" alt="スクリーンショット 2023-08-17 16 41 52" src="https://github.com/NUTFes/FinanSu/assets/115447919/4ab43a22-b7f5-430b-8b32-b3e8fe28f747">

# テスト項目

- `docker compose down -v`でdockerのイメージを削除してから`docker compose up`をする

- [ ] 購入報告の一覧ページで表示されるか
- [ ] 詳細モーダルに表示されるか
- [ ] 追加、編集ができるか
- [ ] csv出力に購入者が追加されているか
- [ ] swaggerでpurchaseReportのapiの動作に問題がないか

# 備考

2023-08-18 13:16 UTC, imaimai17468 requested changes
動作問題なし！
微修正のレビューを出したので修正お願いします

2023-08-18 13:16 UTC, imaimai17468 commented on view/next-project/src/utils/api/purchaseReport.ts
> -  const userID = data.userID;
purchaseReport要素を消すなら、このファイルは削除して、`api_methods.ts`のgetとputを使っちゃった方がいいね

2023-08-18 13:16 UTC, imaimai17468 commented on view/next-project/src/pages/purchasereports/index.tsx
> +      <Card w='w-full'>
このページについて、今は期限の方でfilterしてると思うんだけど、作成日で年を切り替えた方が他のページとも統一されるし直感にそぐうと思う！

2023-08-19 08:49 UTC, Kubosaka commented on view/next-project/src/utils/api/purchaseReport.ts
> -  const userID = data.userID;
[9e6ff7e](https://github.com/NUTFes/FinanSu/pull/642/commits/9e6ff7ea97eae6a218fbed213505cf2613693a89)

2023-08-19 08:49 UTC, Kubosaka commented on view/next-project/src/pages/purchasereports/index.tsx
> +      <Card w='w-full'>
[ef091fc](https://github.com/NUTFes/FinanSu/pull/642/commits/ef091fcdef233dc729a8170edc64b28aa2e1bf55)
[8be6b42](https://github.com/NUTFes/FinanSu/pull/642/commits/8be6b429c12eb2ef86ed78e62349990ac792c2c0)

2023-08-20 21:41 UTC, imaimai17468 approved these changes
LGTM!

2023-08-21 00:57 UTC, merged