[feat] add validation  (#650)
NUTFes/FinanSu pull request #654
Opened 2023-11-11 15:54 UTC by TkymHrt

# 対応Issue

resolve #650 

# 概要

購入物品の登録の際に、物品名を入力せずに申請の確認へ進める仕様を改善。
物品名が未入力の場合には申請の確認ボタンがDisabledになるようにしました。

# 画面スクリーンショット等

### **入力前**
![FireShot Capture 137 - 購入申請一覧 - localhost](https://github.com/NUTFes/FinanSu/assets/131145590/4f7bd24e-9197-49cf-83ca-a66dc8373ae5)
###  **入力後**
![FireShot Capture 138 - 購入申請一覧 - localhost](https://github.com/NUTFes/FinanSu/assets/131145590/6721cac8-d108-4adc-9fa7-25e4792be8c5)

# テスト項目

- [ ]  最初に購入物品の登録モーダルを開くと、「申請の確認」ボタンが押せない。

- [ ] 「物品名」のフォームになにかしら入力すると「申請の確認」ボタンが押せる。

2023-11-12 05:21 UTC, Kubosaka requested changes
早急な対応ありがとうございます！
今のままだと複数の購入物品を登録する時バリデーションがかからないので修正お願いします。
次へ,申請の確認ボタンを `disabled={props.formDataList[activeStep - 1].item.trim() === ''}`したら項目ごとにdisabledかけれるよ。
<img width="746" alt="スクリーンショット 2023-11-12 14 13 58" src="https://github.com/NUTFes/FinanSu/assets/115447919/d81f0588-c825-43cb-9159-5ab0ec1a2c17">

2023-11-12 05:21 UTC, Kubosaka commented on view/next-project/src/components/purchaseorders/PurchaseOrderAddModal.tsx
> +                        disabled={itemName.trim() === ''}
useState使わなくてもこれで各itemの名前が未入力でボタンdisabledできると思う.
`disabled={props.formDataList[activeStep - 1].item.trim() === ''}`

2023-11-13 09:39 UTC, TkymHrt commented on view/next-project/src/components/purchaseorders/PurchaseOrderAddModal.tsx
> +                        disabled={itemName.trim() === ''}
修正しました！

2023-11-14 06:30 UTC, imaimai17468 approved these changes
![LGTM](https://storage.googleapis.com/lgtm-ea733.appspot.com/lgtm/8244718)

2023-11-14 06:30 UTC, imaimai17468 commented on view/next-project/src/components/purchaseorders/PurchaseOrderAddModal.tsx
> +                        disabled={props.formDataList[activeStep - 1].item.trim() === ''}
trimで空白のみの場合も取り除けてるのいいね！

2023-11-14 11:21 UTC, Kubosaka approved these changes
LGTM

2023-11-14 11:21 UTC, merged