購入申請の年度更新
NUTFes/FinanSu pull request #660
Opened 2023-11-18 05:04 UTC by Kubosaka

resolve #652 

# 概要

- 年度一覧(year_periods)テーブルの作成
  - カラム year_id:年id, started_at: 年度の開始日, ended_at: 年度の終了日
- 年度一覧(year_periods)テーブルのAPI作成
  - GET `/year/periods` year_periodsを取得
  - POST /year/periods` year_periodsの作成
  - PUT  /year/periods/:id` year_periodsの更新
  - DELETE /year/periods/:id` year_periodsの削除
- 年度一覧ページの作成
  - `http://localhost:3000/year_periods` 
  - developerとadminのみ閲覧可能
  - 年度一覧の表示 
  - 年度の作成
  - 年度の編集
  - 年度の削除
- 購入申請の年度レコードを取得するAPIの作成
  - GET `/purchaseorders/details/:year` yearで指定した年度のレコード取得 
  - year_periodsの開始日時と終了日時に作成されたレコードをその年のレコードとしています
- 購入申請ページの修正
  -  年度フィルター機能削除 → APIを作成したため
  - 年度をyaer_periodsから選択するように
-  年度の選択をyear_periodsから選択- 新しく作成したAPIのswagger追加

# 画面スクリーンショット等

年度一覧ページ
<img width="1470" alt="スクリーンショット 2023-11-18 13 45 14" src="https://github.com/NUTFes/FinanSu/assets/115447919/187b5143-8ac5-4a8d-847b-89480838bac0">

# テスト項目

- `http://localhost:3000/year_periods`で年度一覧ページが表示されるか(開発者or管理者でログイン)
- 年度一覧ページで年度の追加、編集、削除ができるか
- 購入申請ページで年度ごとに表示できるか
- 購入申請ページで年度一覧に登録した年度が選択できるか

# 備考
- 新しくテーブルを作成したため、DBのスキーマを更新しくて下さい
- `docker compose down -v` → `docker compose up --build`
- 新しくdate-fnsをインストールしたため必要ならnpm installして下さい
-  year_periodsの開始日時と終了日時に作成されたレコードをその年のレコードとしています
- 他不明な点があれば聞いて下さい

2023-11-18 06:36 UTC, imaimai17468 requested changes
コード側チェックしました（動作他の人頼みます）
あとcommitにprefixをつけてください！

2023-11-18 06:36 UTC, imaimai17468 commented on view/next-project/src/type/common.ts
> +export interface YearPeriods {
1つの年度を示す型なのに複数形は違和感があります

```suggestion
export interface YearPeriod {
```

2023-11-18 06:36 UTC, imaimai17468 commented on view/next-project/src/pages/year_periods/index.tsx
> +  yearPeriods: YearPeriods[];
単数系にすることで、yearPeriodsはYearPeriod型の配列なんだなと意味が通りやすくなります

```suggestion
  yearPeriods: YearPeriod[];
```

YearPeriods[]だと年度が複数入ったものの配列（2次元配列）なんだなと勘違いしてしまう可能性があります

2023-11-18 06:36 UTC, imaimai17468 commented on view/next-project/src/pages/year_periods/index.tsx
> +        endedAt: yearPeriod.endedAt && new Date(yearPeriod.endedAt).toLocaleDateString('ja'),
この書き方だと`yearPeriod.startedAt`がundefined(falsy)な場合はstartedAt=undefinedとなってしまいますが想定した実装ですか？
```suggestion
        startedAt: yearPeriod.startedAt || new Date(yearPeriod.startedAt).toLocaleDateString('ja'),
        endedAt: yearPeriod.endedAt || new Date(yearPeriod.endedAt).toLocaleDateString('ja'),
```
ではありませんか？

2023-11-18 06:36 UTC, imaimai17468 commented on view/next-project/src/pages/purchaseorders/index.tsx
> +    yearPeriods ? String(yearPeriods[yearPeriods.length - 1].year) : '2024',
yearPeriodsがない場合の値をリテラルにすると今後また修正する必要があるので、動的に現在の日付を取得してその年を入れた方が今後楽だと思います

2023-11-18 06:36 UTC, imaimai17468 commented on view/next-project/src/pages/year_periods/index.tsx
このページだけスネークケースなのには何か意図はありますか？
TSは基本キャメルケースにしたいです（できれば他のページも）

2023-11-21 12:01 UTC, KazumaSun commented on view/next-project/src/components/year_periods/AddModal.tsx
> +      <h1 className='mx-auto mb-10 w-fit text-xl text-black-600'>募金の登録</h1>
[誤字]募金の登録　→　年度の登録

2023-11-21 12:06 UTC, KazumaSun reviewed
動作自体は正常でした．
年度の重複のチェックは検討してみて(基本的にいじるのが運営側だから，操作説明はしっかり行って，将来課題にしてもよき)

2023-11-21 12:06 UTC, KazumaSun commented on view/next-project/src/components/year_periods/AddModal.tsx
> +    };
既存の年度があった場合のチェックをやった方がいいかも

2023-11-21 12:06 UTC, KazumaSun commented on view/next-project/src/components/year_periods/EditModal.tsx
> +
ここも同様
既存の年度があった場合のチェックをやった方がいいかも

2023-11-21 12:06 UTC, KazumaSun commented on view/next-project/src/components/year_periods/AddModal.tsx
> +      <h1 className='mx-auto mb-10 w-fit text-xl text-black-600'>募金の登録</h1>
[誤字]募金の登録　→　年度の登録

2023-11-23 15:44 UTC, Kubosaka commented on view/next-project/src/type/common.ts
> +export interface YearPeriods {
修正しました [[fix]type名変更](https://github.com/NUTFes/FinanSu/pull/660/commits/0668b50cd8e3e3ab0a9718d1adb9bcbb8d3be4bd)

2023-11-23 15:44 UTC, Kubosaka commented on view/next-project/src/pages/year_periods/index.tsx
> +  yearPeriods: YearPeriods[];
修正しました [[fix]type変更に伴う年度一覧ページ修正](https://github.com/NUTFes/FinanSu/pull/660/commits/4e4e0d002abb90ca58a57f6b80894ade19be8473)

2023-11-23 15:44 UTC, Kubosaka commented on view/next-project/src/pages/year_periods/index.tsx
> +        endedAt: yearPeriod.endedAt && new Date(yearPeriod.endedAt).toLocaleDateString('ja'),
修正しました [[fix]type名変更](https://github.com/NUTFes/FinanSu/pull/660/commits/0668b50cd8e3e3ab0a9718d1adb9bcbb8d3be4bd) [[fix]レコードが0の場合の処理追加](https://github.com/NUTFes/FinanSu/pull/660/commits/2f29a6c71b8aa27d174ccac85925bca655872157)
yearPeriodの型がこれまでだとyearPeriod.startedAtがundefinedの可能性があったため上のようにしていました。

2023-11-23 15:44 UTC, Kubosaka commented on view/next-project/src/pages/purchaseorders/index.tsx
> +    yearPeriods ? String(yearPeriods[yearPeriods.length - 1].year) : '2024',
修正しました [[fix]年度レコードがない際のエンドポイントを動的に変更](https://github.com/NUTFes/FinanSu/pull/660/commits/ee39f86b603d4b383cecf4bd94bdf2a1be37edc9)

2023-11-23 15:45 UTC, Kubosaka commented on view/next-project/src/pages/year_periods/index.tsx
修正しました [[fix]変数名の変更とディレクトリ名変更](https://github.com/NUTFes/FinanSu/pull/660/commits/8da8ebd6d37eaa71fb7d58014a3db8a0eecacaf9)
募金ページはスネークケースみたいです。`/fund_information`

2023-11-23 15:47 UTC, Kubosaka commented on view/next-project/src/components/year_periods/AddModal.tsx
> +    };
修正しました [[feat]登録モーダルの登録済みの年度のバリデーション追加](https://github.com/NUTFes/FinanSu/pull/660/commits/69d779566c379698428acf2d977a330cb9f9b896)
<img width="728" alt="スクリーンショット 2023-11-24 0 46 18" src="https://github.com/NUTFes/FinanSu/assets/115447919/6e263b0d-4046-460d-80e7-c131c5454a59">

2023-11-23 15:47 UTC, Kubosaka commented on view/next-project/src/components/year_periods/EditModal.tsx
> +
修正しました [[fix]編集モーダルも年度のバリデーション追加](https://github.com/NUTFes/FinanSu/pull/660/commits/3e309a6afa9397ff18b7c9d9625a84e5c1da85a8)

2023-11-29 15:08 UTC, imaimai17468 commented on view/next-project/src/pages/year_periods/index.tsx
> +        endedAt: yearPeriod.endedAt && new Date(yearPeriod.endedAt).toLocaleDateString('ja'),
> yearPeriodの型がこれまでだとyearPeriod.startedAtがundefinedの可能性があったため上のようにしていました

なるほど、ずっと「startedAtが”ない場合”は仮のDateをいれる」かと思ってたんですが、「startedAtが"ある場合"は日本語の時間にする」みたいな処理だったんですね、誤読でした

2023-11-29 15:09 UTC, imaimai17468 commented on view/next-project/src/pages/year_periods/index.tsx
[want]
できれば統一したいですね

2023-11-29 15:09 UTC, imaimai17468 approved these changes
![LGTM](https://storage.googleapis.com/lgtm-ea733.appspot.com/lgtm/8246168)

2023-12-10 13:33 UTC, KazumaSun approved these changes
LGTM

2023-12-10 13:40 UTC, merged