[fix]編集モーダルでユーザーが反映されないバグ修正
NUTFes/FinanSu pull request #662
Opened 2023-11-28 15:26 UTC by dyusuke3263

# 対応Issue

resolve #647 

# 概要
協賛活動の編集モーダル変更がうまく反映されないバグの修正。

# 画面スクリーンショット等
![image](https://github.com/NUTFes/FinanSu/assets/133088920/554dcb4b-9611-4a38-912a-5deeb0ebaa1e)

- `URL`
スクリーンショット

# テスト項目

-協賛活動の編集モーダルで担当者を変更し、変更が反映されているか確認する
-
-

# 備考

2023-12-08 01:58 UTC, imaimai17468 approved these changes
抽出部分LGTMだと思います
valueに値を入れるか/optionにseletcted属性をつけて選択済みにするかは @Kubosaka の判断に任せます！

![LGTM](https://storage.googleapis.com/lgtm-ea733.appspot.com/lgtm/8250473)

2023-12-10 07:28 UTC, Kubosaka requested changes
動作は問題なしです。
少し追加で修正して欲しいので、お願いします！

2023-12-10 07:28 UTC, Kubosaka commented on view/next-project/src/components/sponsoractivities/EditModal.tsx
ブラウザで
```
Warning: Use the `defaultValue` or `value` props on <select> instead of setting `selected` on <option>.
```
のwarningが出ているので(おそらく前から)、せっかくなんで、初期値はselectタグのvalueで設定しましょうか。
自分のドラフトの[PR](https://github.com/NUTFes/FinanSu/pull/661)を参考にやってみてください。
不明な点があれば気軽に聞いてください。

2024-02-17 05:28 UTC, KazumaSun approved these changes
動作よきです。
くぼが指摘した箇所の修正が終わればLGTMです

2024-03-21 01:32 UTC, merged