[fix] 登録されたデータが編集モーダルに反映されるよう修正
NUTFes/FinanSu pull request #696
Opened 2024-03-05 07:07 UTC by TkymHrt

# 対応Issue

resolve #663 

# 概要

Issue内容は、担当者が各局の一番上の人になるバグの解消です。
しかし、教員の所属・教員名・担当者の局の項目でも同様のバグが発生していたため、まとめて修正しました。
修正内容は、各項目の初期値として登録される値を、既に登録されている内容から参照するように変更しました。

# 画面スクリーンショット等

![FireShot Capture 169 - 学内募金一覧 - localhost](https://github.com/NUTFes/FinanSu/assets/131145590/2051d018-ffa8-47e9-b8c1-761636f41bc2)

![FireShot Capture 170 - 学内募金一覧 - localhost](https://github.com/NUTFes/FinanSu/assets/131145590/bdf4e270-862d-424a-99ed-b855d8e63c95)

# テスト項目

- FinanSuをローカルで立ち上げ、`http://localhost:3000/fund_informations` へアクセスできることを確認する。
- 登録項目の編集ボタンを押し、編集モーダルが開くことを確認する。
- 各項目を初期値以外のものに設定し、登録ボタンを押す。（スクショ画像を参考にしてください。）
- 登録できたことを確認して再度、編集ボタンを押し、登録内容が初期化されていないかを確認する。
(各項目が全て1番目の要素に初期化されていないか。)

# 備考

2024-03-19 05:25 UTC, hikahana reviewed
動作確認できました。
ちょっと気になったところコメントしてます

2024-03-19 05:25 UTC, hikahana commented on view/next-project/src/components/fund_information/EditModal.tsx
> +  }, [departmentID, props.teachers]);
defaultValueなくてもいけるのではないでしょうか
```
  useEffect(() => {
    const selectedTeacher = props.teachers.find(
      (teacher) => teacher.id === props.fundInformation.teacherID,
    );
    if (selectedTeacher?.id) {
      setDepartmentID(selectedTeacher.departmentID);
      setFormData({ ...formData, teacherID: selectedTeacher.id });
    } else {
      const relatedTeachers = props.teachers.filter(
        (teacher) => teacher.departmentID === departmentID,
      );
      if (relatedTeachers) {
        setFormData({ ...formData, teacherID: relatedTeachers[0].id || 0 });
      }
    }
  }, [departmentID, props.teachers]);
```

2024-03-20 11:07 UTC, hikahana approved these changes
![LGTM](https://storage.googleapis.com/lgtm-ea733.appspot.com/lgtm/8249626)

2024-03-21 02:50 UTC, Kubosaka requested changes
対応ありがとうございます！
少し、コメントしました！
動作おかしいやこっちのがいいなどあれば気軽に言ってください

2024-03-21 02:50 UTC, Kubosaka commented on view/next-project/src/components/fund_information/EditModal.tsx
> +  }, [departmentID, props.teachers]);
すごく面白いロジックで色々試してくれたと思います！
ただ、ロジックがわかりにくい(可読性)の観点から以下の方がわかりやすいかなって思いました！

useStateでteacherとdepartmentIDを定義
それぞれ初期値にpropsでデータを渡されたを入れる
teacher.departmentID とdepartmentIDが違う場合のみフィルターをかける

```
  const defaultTeacher = props.teachers.find(
    (teacher) => teacher.id === props.fundInformation.teacherID,
  );
  const [teacher, setTeacher] = useState<Teacher | undefined>(defaultTeacher);
  const [departmentID, setDepartmentID] = useState<number>(defaultTeacher?.departmentID || 1);

  useEffect(() => {
    if (teacher?.departmentID !== departmentID) {
      const relatedTeachers = props.teachers.filter(
        (teacher) => teacher.departmentID === departmentID,
      );
      relatedTeachers &&
        setFormData({
          ...formData,
          teacherID: relatedTeachers[0]?.id || 0,
        });
      setTeacher(relatedTeachers[0]);
    }
  }, [departmentID]);
```

2024-03-21 07:42 UTC, TkymHrt commented on view/next-project/src/components/fund_information/EditModal.tsx
> +  }, [departmentID, props.teachers]);
修正しました！

2024-03-22 07:39 UTC, Kubosaka approved these changes
LGTM

2024-03-22 07:39 UTC, merged