[feat]協賛活動の領収書のPDF出力
NUTFes/FinanSu pull request #709
Opened 2024-03-19 09:24 UTC by KazumaSun

# 対応Issue

resolve #706 

# 概要

協賛活動の領収書のPDF出力を実装

# 画面スクリーンショット等

![スクリーンショット 2024-03-19 181937](https://github.com/NUTFes/FinanSu/assets/68796591/a48e4ba0-7dc6-4680-b849-bbfbb30ebd50)

[領収書_20240319_テスト企業.pdf](https://github.com/NUTFes/FinanSu/files/14648363/_20240319_.pdf)

# テスト項目

- [ ] 協賛活動ページの詳細モーダルを表示
- [ ] モーダル下部の「領収書の作成」を押下
- [ ] 入金日を入力し、「領収書のダウンロード」を押下
- [ ] 領収書のPDFがダウンロードされる
-
-

# 備考

2024-03-20 09:14 UTC, hikahana commented on view/next-project/src/components/sponsoractivities/OpenPaymentDayModalButton.tsx
> +    // props.setIsOpen(false)
```suggestion

```
削除忘れだと思います

2024-03-20 09:21 UTC, hikahana commented on view/next-project/src/components/sponsoractivities/OpenPaymentDayModalButton.tsx
> +  isDisabled?: boolean;
```suggestion
  isDisabled: boolean;
```
undefinedを許容しなくて動くと思います

2024-03-20 09:32 UTC, hikahana commented on view/next-project/src/components/sponsoractivities/PaymentDayModal.tsx
> +          入金日の入力
```suggestion
          入金日を入力
```
どっちでもよさげ、ちょっと気になっただけです

2024-03-21 05:42 UTC, hikahana approved these changes
![LGTM](https://storage.googleapis.com/lgtm-ea733.appspot.com/lgtm/8249585)

2024-03-22 08:38 UTC, Kubosaka requested changes
領収書は問題なしです。
購入報告書作成を編集してしまっているため、正常に出力できるように修正して欲しいです。

2024-03-22 08:38 UTC, Kubosaka commented on view/next-project/src/utils/createPurchaseReportPdf.ts
購入報告の報告書の見た目がおかしいため修正してください
<img width="770" alt="スクリーンショット 2024-03-22 17 36 17" src="https://github.com/NUTFes/FinanSu/assets/115447919/7b2e5fff-df9e-4748-b969-4fcdca101634">

2024-03-22 12:09 UTC, KazumaSun commented on view/next-project/src/utils/createPurchaseReportPdf.ts
@Kubosaka 
修正しました。

2024-03-28 01:14 UTC, Kubosaka approved these changes
LGTM

2024-03-28 01:15 UTC, merged