請求書（PDF）作成機能の追加＠
NUTFes/FinanSu pull request #712
Opened 2024-03-20 10:25 UTC by TkymHrt

# 対応Issue

resolve #0

# 概要

# 画面スクリーンショット等

- `URL`
スクリーンショット

# テスト項目

-
-
-

# 備考

2024-03-20 11:15 UTC, hikahana commented
請求書の概要部分に協賛スタイルのオプションを追記(モノクロ、カラー等)

請求期限に関してはフォームを新たに作成して、期限を入力させる。
参考にのぶのPRを貼る
https://github.com/NUTFes/FinanSu/pull/709

2024-03-20 11:25 UTC, hikahana commented
備考はモーダルの備考ではない。
新たに入力させる

2024-03-22 08:16 UTC, hikahana reviewed
動作okでした！
半分くらい個人的に気になったところだけどコメントつけたので時間ある時にでも目を通してください

2024-03-22 08:16 UTC, hikahana commented on view/next-project/src/utils/createSponsoractivitiesReceiptPDF.tsx
> +            <Text style={[styles.commonTableCol, styles.tableColHeader_L]}></Text>
```suggestion
            <Text style={[styles.commonTableCol, styles.tableColHeader_S]} />
            <Text style={[styles.commonTableCol, styles.tableColHeader_L]} />
```
私はこっちのほうが好き
直すかはお任せします

2024-03-22 08:16 UTC, hikahana commented on view/next-project/src/utils/createSponsoractivitiesReceiptPDF.tsx
> +  await asPdf.toBlob();
```suggestion

```
多分なくても動く

2024-03-22 08:16 UTC, hikahana commented on view/next-project/src/components/sponsoractivities/AddPdfDetailModal.tsx
> +            請求書ダウンロード
```suggestion
            ダウンロード
```
請求書作成クリックして、請求書ダウンロードがでてくるのが請求書の圧を感じた

2024-03-28 01:31 UTC, Kubosaka commented on view/next-project/src/utils/createSponsoractivitiesReceiptPDF.tsx
> +                  <Text>〒940-2137</Text>
940-2137も上富岡町の郵便番号で合ってるよ、24がどっちなのかは確認した方がいいかも

2024-03-28 01:33 UTC, Kubosaka requested changes
2点お願いします。
1. ダウンロードボタンを押したら、モーダルは消えた方がいいかもですね。
2. コンフリクト解消をお願いできますか？
請求書と領収書作成ボタンが並ぶ感じで大丈夫です。

2024-03-29 08:39 UTC, Kubosaka approved these changes
LGTM

2024-03-29 08:40 UTC, merged